arm_robot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  effort_joints_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
    gains:
      joint_1: {p: 150.0, i: 0.0, d: 0.0} 
      joint_2: {p: 150.0, i: 0.0, d: 0.0}
      joint_3: {p: 150.0, i: 0.0, d: 0.0}
      joint_4: {p: 50.0, i: 0.0, d: 0.0}

  position_joints_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - joint_51
      - joint_52
    gains:
      joint_51: {p: 150.0, i: 0.0, d: 0.0}
      joint_52: {p: 150.0, i: 0.0, d: 0.0}