# Publishing joint states
ros_control_tester:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

# Defining joint controllers
# Effort controllers can only control one joint.
  joints_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
        - toe_foot_joint
        - foot_leg_joint
        - leg_arm_joint
    gains:
      toe_foot_joint: {p: 200.0, i: 0.0, d: 0.0}
      foot_leg_joint: {p: 100.0, i: 0.0, d: 1.0}
      leg_arm_joint: {p: 100.0, i: 0.0, d: 0.0}

# Increasing p means reach target faster but with higher overshoot
# With p = 50 for the toe_foot_joint, the robot arm would wobble when moving but whith p = 1000 it would violently shake at the start
# Adding a d value for toe_foot_joint makes it wobble on start
# Removing d value from foot_leg_joint makes it wobble